version: '3.5'

services:
  webnsurf-react-web-dev:
    container_name: ${STACK}-dev_FE
    build:
      context: .
      dockerfile: pipelines/Dockerfile.dev
    image: ${IMAGE}-dev:latest
    ports:
      - ${PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.webnsurf-react-web-dev-redirect.rule: Host(`${DEV_URL}`)
      traefik.http.routers.webnsurf-react-web-dev-redirect.middlewares: https-redirect@file
      traefik.http.routers.webnsurf-react-web-dev-redirect.entrypoints: web

      traefik.http.routers.webnsurf-react-web-dev.rule: Host(`${DEV_URL}`)
      traefik.http.routers.webnsurf-react-web-dev.entrypoints: websecure
      traefik.http.routers.webnsurf-react-web-dev.tls: true
    volumes:
      - /app/dist
      - /app/node_modules
      - $PWD:/app
    env_file: .env
    environment:
      NODE_ENV: development
      RUNTIME_ENV: development
      FROM_DOCKER: 'true'

networks:
  default:
    external:
      name: webnsurf_network
