version: '3.5'

services:
  webnsurf-react-web:
    container_name: ${NAME}
    image: ${IMAGE}:${BUILD_ID}
    tty: true
    ports:
      - ${PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.webnsurf-react-web-redirect.rule: Host(`${URL}`)
      traefik.http.routers.webnsurf-react-web-redirect.entrypoints: web
      traefik.http.routers.webnsurf-react-web-redirect.middlewares: https-redirect@file

      traefik.http.routers.webnsurf-react-web.rule: Host(`${URL}`)
      traefik.http.routers.webnsurf-react-web.entrypoints: websecure
      traefik.http.routers.webnsurf-react-web.tls: true
    env_file: ${ENV_FILE}

networks:
  default:
    external:
      name: webnsurf_network
